Find dependencies when including tmxparserConfig.cmake
hunter-packages/tmxparser pull request #2
Opened 2019-04-18 07:04 UTC by sjdrc

Hey, I missed modifying this file when hunterising this package. Let me know if you want me to do a rebase to clean up the history.

2019-04-18 13:23 UTC, ruslo requested changes

2019-04-18 13:23 UTC, ruslo commented on cmake/tmxparserConfig.cmake.in
> +find_dependency(ZLIB REQUIRED)
We need `CONFIG` here to not to fall into system version:
- https://docs.hunter.sh/en/latest/packages/pkg/ZLIB.html

2019-04-18 13:23 UTC, ruslo commented on cmake/tmxparserConfig.cmake.in
> +find_dependency(tinyxml2 REQUIRED)
Same:
- https://docs.hunter.sh/en/latest/packages/pkg/tinyxml2.html

2019-04-20 23:40 UTC, sjdrc commented
@ruslo I think this is ready to be merged

2019-04-21 11:49 UTC, merged

2019-04-21 11:50 UTC, ruslo commented
Released: https://github.com/hunter-packages/tmxparser/releases/tag/v2.1.0-ab4125b-p1